### ISSUE TITLE
Oracle tests failing

### ISSUE THREAD

**Issue by Isaac-DeFrain** [garethtdavies/zkAppPool#37]
I tried for some time but could only ever get the first oracle test to pass

**Comment by garethtdavies** [comment]
Thank you, and sorry I just saw this issue and PR as I was cleaning up this repo. Looks like as the signature verification changed in a recent version of snarkyJS this broke as I needed to update the oracle. That's all done now with the update to 0.9.6 , and the tests pass. Now I'll try to merge in your PR as you updated other deprecated items, after I deal with the merge conflicts 😕

**Comment by garethtdavies** [comment]
If you still have issues with a failing test please reopen this issue, but will close for now as I can get everything to pass running 0.9.6.
